### ISSUE TITLE
Methods printing to the console rather than returning an error. 

### ISSUE THREAD

**Issue by ahdisease** [ahdisease/Bird-Finder#8]
Methods in [BirdController](https://github.com/ahdisease/Bird-Finder/blob/main/dotnet/Capstone/Controllers/BirdController.cs) are generally printing to the console rather than returning an error. I'm good to correct this in the database-rework branch, but I wanted to acknowledge that.

Methods:
- ListAllBirds
- getRandomBird
- getBirdsInList
- getBirdByZip

_Originally posted by @ahdisease in https://github.com/ahdisease/Bird-Finder/pull/7#discussion_r1367610039_

**Comment by kimbambala** [comment]
Done
